services:
  backend:
    image: your-image-backend
    container_name: sge-backend
    build: ./backend
    ports:
      - "3000:3000" # Backend en 3000
    environment:
      NODE_ENV: production
    networks:
      - sge-network

  frontend:
    image: your-image-frontend
    container_name: sge-frontend
    build: ./frontend/sge-app
    ports:
      - "80:80" # El frontend estará disponible en el puerto 80
    depends_on:
      - backend
    networks:
      - sge-network

networks:
  sge-network:
    driver: bridge
