services:
  backend:
    image: your-image-backend
    container_name: sge-backend
    build: ./backend
    ports:
      - "3000:3000" # Backend en 3000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    networks:
      - sge-network

  frontend:
    image: your-image-frontend
    container_name: sge-frontend
    build: ./frontend/sge-app
    ports:
      - "5173:5173" # Frontend en 5173
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - sge-network

networks:
  sge-network:
    driver: bridge
